apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: graylog-storage-standard
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
reclaimPolicy: Delete
volumeBindingMode: Immediate