apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-deployment
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
        ports:
        - containerPort: 9200
        env:
          - name: http.host
            value: 0.0.0.0
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: elasticsearch
  name: elasticsearch
spec:
  type: ClusterIP
  ports:
  - name: es-port
    port: 9200
    targetPort: 9200
  selector:
    app: elasticsearch