apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog-deployment
  labels:
    app: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
      - name: graylog
        image: graylog/graylog:3.3
        ports:
        - containerPort: 1514
        - containerPort: 9000
        - containerPort: 12201
        env:
          - name: GRAYLOG_HTTP_EXTERNAL_URI
            value: http://www.graylog.local:9000/
          - name: GRAYLOG_ELASTICSEARCH_HOSTS
            value: http://elasticsearch:9200
          - name: GRAYLOG_MONGODB_URI
            value: mongodb://mongo:27017/graylog

---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: graylog
    name: graylog
  spec:
    type: LoadBalancer
    ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
      # nodePort: 30003
    - name: "12201"
      port: 12201
      targetPort: 12201
      # nodePort: 30004
    selector:
      app: graylog